
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 18 23:35:19 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MONKEY = 52;
  public static final int GREATERTHAN = 32;
  public static final int CONST = 11;
  public static final int CHAR = 4;
  public static final int GREATEROREQUAL = 34;
  public static final int CASE = 23;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 48;
  public static final int CONTINUE = 22;
  public static final int RARRAYBRACE = 45;
  public static final int MINUS = 26;
  public static final int RPAREN = 49;
  public static final int SEMICOLON = 41;
  public static final int AND = 36;
  public static final int EQUALTO = 30;
  public static final int OR = 37;
  public static final int LESSTHAN = 33;
  public static final int COMMA = 42;
  public static final int BOOL = 5;
  public static final int CLASS = 8;
  public static final int INC = 39;
  public static final int DIV = 28;
  public static final int LESSOREQUAL = 35;
  public static final int PLUS = 25;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 38;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NUMBER = 3;
  public static final int MOD = 29;
  public static final int BREAK = 7;
  public static final int IDENT = 2;
  public static final int VOID = 20;
  public static final int LARRAYBRACE = 44;
  public static final int SWITCH = 13;
  public static final int COLON = 51;
  public static final int LBRACE = 46;
  public static final int ELSE = 10;
  public static final int POINT = 43;
  public static final int ENUM = 9;
  public static final int READ = 18;
  public static final int WHILE = 15;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 21;
  public static final int PROG = 6;
  public static final int QUESTION = 50;
  public static final int STRING = 24;
  public static final int HASHTAG = 53;
  public static final int DEC = 40;
  public static final int PRINT = 17;
  public static final int DO = 14;
}

